package project;

public  enum CourtType{
     COMMON,
     CONSTITUTIONAL_TRIBUNAL,
     SUPREME,
     NATIONAL_APPEAL_CHAMBER,
     PROVINCIAL_ADMINISTARTIVE_COURT,
     SUPREME_ADMINISTARTIVE_COURT;
}

